# Generated by Django 3.0.3 on 2020-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('user', models.CharField(default='8080', max_length=100, primary_key=True, serialize=False)),
                ('score', models.CharField(default=0, max_length=10000000)),
            ],
        ),
    ]
